{"uuid": "d9173444-1a0a-4e62-ab84-bd678a07a888", "children": ["a7af4e86-ba6f-47f2-bfcb-65d8e4a2c0ab"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User icon is not presented, probably unauthorised user\n", "trace": "  File \"d:\\python\\stepik_auto\\stepik_lessons\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\stepik_auto\\stepik_lessons\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\stepik_auto\\stepik_lessons\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 778, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\python\\stepik_auto\\stepik_lessons\\module_5\\test_product_page.py\", line 36, in setup\n    login_page.should_be_authorized_user()\n  File \"D:\\python\\stepik_auto\\stepik_lessons\\module_5\\pages\\base_page.py\", line 52, in should_be_authorized_user\n    assert self.is_element_present(*BasePageLocators.USER_ICON), \"User icon is not presented,\" \\\n"}, "start": 1623840347341, "stop": 1623840361225}], "start": 1623840347341, "stop": 1623840361270}